/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElInput: typeof import('element-plus/es')['ElInput']
    HeaderSetting: typeof import('./src/components/table/HeaderSetting.vue')['default']
    LineChart: typeof import('./src/components/chart/LineChart.vue')['default']
    NewPiTable: typeof import('./src/components/table/newPiTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/test.vue')['default']
  }
}
